[package]
name = "tiva_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
tm4c123x = "0.9"
usb-device = "0.2"
usbd-serial = "0.1"

[build-dependencies]
cc = "1.0"

[profile.release]
opt-level = "s"
lto = true
